# Generated by Django 2.0.7 on 2018-07-14 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHumansMember',
            fields=[
                ('oh_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=256)),
                ('refresh_token', models.CharField(max_length=256)),
                ('expiration_time', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oh_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
